# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('humanReadable', models.CharField(max_length=30)),
                ('standardMapping', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
