# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
