# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_agencyallowedfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='hash',
            field=models.CharField(default='awesome', max_length=40),
        ),
    ]
