# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_agency_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='hash',
        ),
    ]
