# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_agency_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
