# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfield',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
