# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_useragency'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='abbr',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
