# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_agency_abbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
